### ISSUE TITLE
Consider using enum for subtitles lang

### ISSUE THREAD

**Issue by nklhtv** [Stremio/stremio-core#208]
Consider using an enum of ISO 639-2 languages for Subtitles lang property.

**Comment by YanivBir** [comment]
Hi @nklhrstv I can handle this.
Could you provide more info regarding this?

**Comment by nklhrstv** [comment]
There is a rust crate that could be used here, called isolang.
Unfortunately, it does not support ISO 639-2. There is an [issue](https://github.com/humenda/isolang-rs/issues/15) for that.
If you could add support for ISO 639-2 in isolang we can use it in stremio-core.
Language names information must be extracted from a trusted source like [loc.gov](https://www.loc.gov/standards/iso639-2/)
[isolang-rs/build.rs](https://github.com/humenda/isolang-rs/blob/master/build.rs) must be modified in order to produce Language enum for ISO 639-2.
You could use [this file](https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt)

**Comment by YanivBir** [comment]
Hi @nklhrstv,
I just read about ISO 639-2 and ISO 639-3 in wiki and [saw](https://en.wikipedia.org/wiki/ISO_639-3) it:
"ISO 639-3 extends the ISO 639-2 alpha-3 codes with an aim to cover all known natural languages."
I made a check for some enum and from ISO 639-2 and find them same in ISO 639-2.
So If ISO 639-3 actually extend ISO 639-2, Why we can't use the enums from ISO 639-3?

**Comment by nklhrstv** [comment]
[this](https://en.m.wikipedia.org/wiki/ISO_639-3) article says "ISO 639-3 is not a superset of ISO 639-2". 
i have to check what we currently use and if we could migrate to a newer standard. postpone any work on this issue until further clarification.

**Comment by nklhtv** [comment]
we will keep using String for this field and try to match against both standards in the ui
