### ISSUE TITLE
Stremio Server setup?

### ISSUE THREAD

**Issue by lonnietc** [Stremio/stremio-core#244]
Hello,

I have used Kodi a lot, but think that Stremio is a bit different as it seems to have a server-client topology.

I would like to set up a Stemio server and client for some offline testing and to get a feel for how everything is done.

The main site says that everything is open source but I am not clear as to if this Repo is the one needed for the server since there seems to be another one for a Stemio-Desktop.

Can you please give some guidance on this?
Thanks in advance.

**Comment by Ivshti** [comment]
Asking this in stremio-shell would be better (this repo is a library holding core logic)

But in practice to set up your own server, you need to do the following

make sure you have nodejs installed and then:
```
wget https://dl.strem.io/four/master/server.js
node server.js
```

It's not documented because prior to the upcoming launch of https://github.com/stremio/stremio-web, there's little point of starting your own server. Once stremio-web is launched, there will be an easier way to do this.
