### ISSUE TITLE
Tv.strem.io

### ISSUE THREAD

**Issue by Rofocale11** [Stremio/stremio-core#657]
Any plan to update tv.strem.io? I was hoping it would fuction like app.strem.io not the web one so the subttitles work and can choose audio track

**Comment by elpiel** [comment]
Hello @Rofocale11 ,
Thank you for opening this issue!

I'm closing this issue as this is not related to core at all and [tv.strem.io](http://tv.strem.io/) was never officially released, it is a testing domain that users randomly stumbled upon, it cannot be updated as the app was rewritten since then and can never include all features of the app.
